// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'dashboard_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$DashboardModelImpl _$$DashboardModelImplFromJson(Map<String, dynamic> json) =>
    _$DashboardModelImpl(
      (json['id'] as num?)?.toInt(),
      json['dateNow'] as String?,
      (json['total'] as num?)?.toDouble(),
      (json['tax'] as num?)?.toDouble(),
      (json['subTotal'] as num?)?.toDouble(),
      (json['foodTotal'] as num?)?.toDouble(),
      (json['beerTotal'] as num?)?.toDouble(),
      (json['wineTotal'] as num?)?.toInt(),
      (json['beverageTotal'] as num?)?.toDouble(),
      (json['liquorTotal'] as num?)?.toDouble(),
      (json['foodCount'] as num?)?.toInt(),
      (json['beerCount'] as num?)?.toInt(),
      (json['wineCount'] as num?)?.toInt(),
      (json['beverageCount'] as num?)?.toInt(),
      (json['liquorCount'] as num?)?.toInt(),
      (json['paymentCreditAmex'] as num?)?.toDouble(),
      (json['paymentCreditDiscover'] as num?)?.toDouble(),
      (json['paymentCreditVisa'] as num?)?.toDouble(),
      (json['paymentCreditMastercard'] as num?)?.toDouble(),
      (json['paymentAccount'] as num?)?.toInt(),
      (json['paymentCash'] as num?)?.toDouble(),
      (json['gratuityCash'] as num?)?.toDouble(),
      (json['paymentCreditAmexCount'] as num?)?.toInt(),
      (json['paymentCreditDiscoverCount'] as num?)?.toInt(),
      (json['paymentCreditVisaCount'] as num?)?.toInt(),
      (json['paymentCreditMastercardCount'] as num?)?.toInt(),
      (json['paymentAccountCount'] as num?)?.toInt(),
      (json['paymentCashCount'] as num?)?.toInt(),
      (json['gratuityCashCount'] as num?)?.toInt(),
      (json['typeDineIn'] as num?)?.toDouble(),
      (json['typePickUp'] as num?)?.toDouble(),
      (json['typeDelivery'] as num?)?.toInt(),
      (json['typeCarryOut'] as num?)?.toInt(),
      (json['typeDineInCount'] as num?)?.toInt(),
      (json['typePickUpCount'] as num?)?.toInt(),
      (json['typeDeliveryCount'] as num?)?.toInt(),
      (json['typeCarryOutCount'] as num?)?.toInt(),
      (json['statusPlaced'] as num?)?.toInt(),
      (json['statusCanceled'] as num?)?.toInt(),
      (json['statusPlacedCount'] as num?)?.toInt(),
      (json['statusCanceledCount'] as num?)?.toInt(),
      (json['employeeNumber'] as num?)?.toInt(),
      (json['employeeHours'] as num?)?.toDouble(),
      (json['totalDiscount'] as num?)?.toDouble(),
      (json['openTables'] as num?)?.toInt(),
      (json['totalVOID'] as num?)?.toDouble(),
      (json['totalOnlyOders'] as num?)?.toDouble(),
      (json['totalTips'] as num?)?.toDouble(),
      (json['paymentCreditCard'] as num?)?.toDouble(),
      (json['otherTotal'] as num?)?.toDouble(),
      (json['otherCount'] as num?)?.toInt(),
      (json['tipsFee'] as num?)?.toInt(),
      (json['wineBeerTotal'] as num?)?.toInt(),
      (json['wineBeerCount'] as num?)?.toInt(),
      json['lastUpdate'] as String?,
      (json['totalOnlyOdersCount'] as num?)?.toInt(),
    );

Map<String, dynamic> _$$DashboardModelImplToJson(
        _$DashboardModelImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'dateNow': instance.dateNow,
      'total': instance.total,
      'tax': instance.tax,
      'subTotal': instance.subTotal,
      'foodTotal': instance.foodTotal,
      'beerTotal': instance.beerTotal,
      'wineTotal': instance.wineTotal,
      'beverageTotal': instance.beverageTotal,
      'liquorTotal': instance.liquorTotal,
      'foodCount': instance.foodCount,
      'beerCount': instance.beerCount,
      'wineCount': instance.wineCount,
      'beverageCount': instance.beverageCount,
      'liquorCount': instance.liquorCount,
      'paymentCreditAmex': instance.paymentCreditAmex,
      'paymentCreditDiscover': instance.paymentCreditDiscover,
      'paymentCreditVisa': instance.paymentCreditVisa,
      'paymentCreditMastercard': instance.paymentCreditMastercard,
      'paymentAccount': instance.paymentAccount,
      'paymentCash': instance.paymentCash,
      'gratuityCash': instance.gratuityCash,
      'paymentCreditAmexCount': instance.paymentCreditAmexCount,
      'paymentCreditDiscoverCount': instance.paymentCreditDiscoverCount,
      'paymentCreditVisaCount': instance.paymentCreditVisaCount,
      'paymentCreditMastercardCount': instance.paymentCreditMastercardCount,
      'paymentAccountCount': instance.paymentAccountCount,
      'paymentCashCount': instance.paymentCashCount,
      'gratuityCashCount': instance.gratuityCashCount,
      'typeDineIn': instance.typeDineIn,
      'typePickUp': instance.typePickUp,
      'typeDelivery': instance.typeDelivery,
      'typeCarryOut': instance.typeCarryOut,
      'typeDineInCount': instance.typeDineInCount,
      'typePickUpCount': instance.typePickUpCount,
      'typeDeliveryCount': instance.typeDeliveryCount,
      'typeCarryOutCount': instance.typeCarryOutCount,
      'statusPlaced': instance.statusPlaced,
      'statusCanceled': instance.statusCanceled,
      'statusPlacedCount': instance.statusPlacedCount,
      'statusCanceledCount': instance.statusCanceledCount,
      'employeeNumber': instance.employeeNumber,
      'employeeHours': instance.employeeHours,
      'totalDiscount': instance.totalDiscount,
      'openTables': instance.openTables,
      'totalVOID': instance.totalVOID,
      'totalOnlyOders': instance.totalOnlyOders,
      'totalTips': instance.totalTips,
      'paymentCreditCard': instance.paymentCreditCard,
      'otherTotal': instance.otherTotal,
      'otherCount': instance.otherCount,
      'tipsFee': instance.tipsFee,
      'wineBeerTotal': instance.wineBeerTotal,
      'wineBeerCount': instance.wineBeerCount,
      'lastUpdate': instance.lastUpdate,
      'totalOnlyOdersCount': instance.totalOnlyOdersCount,
    };
