// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'super_restaurant_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$SuperRestaurantModelImpl _$$SuperRestaurantModelImplFromJson(
        Map<String, dynamic> json) =>
    _$SuperRestaurantModelImpl(
      id: (json['id'] as num?)?.toInt(),
      restaurantname: json['restaurantname'] as String?,
      addresslinE1: json['addresslinE1'] as String?,
      addresslinE2: json['addresslinE2'] as String?,
      crossstreet: json['crossstreet'] as String?,
      city: json['city'] as String?,
      state: json['state'] as String?,
      zip: json['zip'] as String?,
      phoneareacode: json['phoneareacode'] as String?,
      phone: json['phone'] as String?,
      faxareacode: json['faxareacode'] as String?,
      fax: json['fax'] as String?,
      minimumdeliveryamount: (json['minimumdeliveryamount'] as num?)?.toInt(),
      minimumcreditcardamount:
          (json['minimumcreditcardamount'] as num?)?.toInt(),
      maximumdeliverydistance:
          (json['maximumdeliverydistance'] as num?)?.toInt(),
      email: json['email'] as String?,
      website: json['website'] as String?,
      foodcategory: json['foodcategory'] as String?,
      description: json['description'] as String?,
      password: json['password'] as String?,
      taxrate: (json['taxrate'] as num?)?.toInt(),
      acceptcheck: json['acceptcheck'] as bool?,
      visa: json['visa'] as bool?,
      mastercard: json['mastercard'] as bool?,
      amex: json['amex'] as bool?,
      discover: json['discover'] as bool?,
      active: json['active'] as bool?,
      gratuity: (json['gratuity'] as num?)?.toInt(),
      deliverycharge: (json['deliverycharge'] as num?)?.toInt(),
      advancenotice: (json['advancenotice'] as num?)?.toInt(),
      printnumber: (json['printnumber'] as num?)?.toInt(),
      drivernumber: (json['drivernumber'] as num?)?.toInt(),
      deliverycommission: (json['deliverycommission'] as num?)?.toInt(),
      deliveryrestaurantid: (json['deliveryrestaurantid'] as num?)?.toInt(),
      emailserver: json['emailserver'] as String?,
      uploadhost: json['uploadhost'] as String?,
      firstorderdiscount: (json['firstorderdiscount'] as num?)?.toInt(),
      cutoffhour: (json['cutoffhour'] as num?)?.toInt(),
      country: json['country'] as String?,
      deliverychargepercentage:
          (json['deliverychargepercentage'] as num?)?.toInt(),
      deliverytippercentage: (json['deliverytippercentage'] as num?)?.toInt(),
      numberofcompliment: (json['numberofcompliment'] as num?)?.toInt(),
      numberofcomplaint: (json['numberofcomplaint'] as num?)?.toInt(),
      priceend: (json['priceend'] as num?)?.toInt(),
      pricestart: (json['pricestart'] as num?)?.toInt(),
      level: (json['level'] as num?)?.toInt(),
      numberofcoupons: (json['numberofcoupons'] as num?)?.toInt(),
      partnerid: (json['partnerid'] as num?)?.toInt(),
      m: (json['m'] as num?)?.toInt(),
      expiration: json['expiration'] as String?,
      mip: (json['mip'] as num?)?.toInt(),
      twitterurl: json['twitterurl'] as String?,
      facebookurl: json['facebookurl'] as String?,
      neighborhood: json['neighborhood'] as String?,
      onlinediscount: (json['onlinediscount'] as num?)?.toInt(),
      egift: json['egift'] as bool?,
      enterpriseid: (json['enterpriseid'] as num?)?.toInt(),
      inclusivetaxrate: (json['inclusivetaxrate'] as num?)?.toInt(),
      wirelesswaiterhost: json['wirelesswaiterhost'] as String?,
      ftpserver: json['ftpserver'] as String?,
      minimumdeliverydinneramount:
          (json['minimumdeliverydinneramount'] as num?)?.toInt(),
      pagename: json['pagename'] as String?,
      pagekey: json['pagekey'] as String?,
      ftpuser: json['ftpuser'] as String?,
      taX3RATE: (json['taX3RATE'] as num?)?.toInt(),
      tmip: (json['tmip'] as num?)?.toInt(),
      ftppassword: json['ftppassword'] as String?,
      deliverystartminutE1: (json['deliverystartminutE1'] as num?)?.toInt(),
      deliverystartminutE2: (json['deliverystartminutE2'] as num?)?.toInt(),
      lunchminute: (json['lunchminute'] as num?)?.toInt(),
      lunchhour: (json['lunchhour'] as num?)?.toInt(),
      deliveryendhouR2: (json['deliveryendhouR2'] as num?)?.toInt(),
      deliveryendhouR1: (json['deliveryendhouR1'] as num?)?.toInt(),
      deliverystarthouR2: (json['deliverystarthouR2'] as num?)?.toInt(),
      deliveryendminutE1: (json['deliveryendminutE1'] as num?)?.toInt(),
      deliveryendminutE2: (json['deliveryendminutE2'] as num?)?.toInt(),
      deliverystarthouR1: (json['deliverystarthouR1'] as num?)?.toInt(),
      status: (json['status'] as num?)?.toInt(),
    );

Map<String, dynamic> _$$SuperRestaurantModelImplToJson(
        _$SuperRestaurantModelImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'restaurantname': instance.restaurantname,
      'addresslinE1': instance.addresslinE1,
      'addresslinE2': instance.addresslinE2,
      'crossstreet': instance.crossstreet,
      'city': instance.city,
      'state': instance.state,
      'zip': instance.zip,
      'phoneareacode': instance.phoneareacode,
      'phone': instance.phone,
      'faxareacode': instance.faxareacode,
      'fax': instance.fax,
      'minimumdeliveryamount': instance.minimumdeliveryamount,
      'minimumcreditcardamount': instance.minimumcreditcardamount,
      'maximumdeliverydistance': instance.maximumdeliverydistance,
      'email': instance.email,
      'website': instance.website,
      'foodcategory': instance.foodcategory,
      'description': instance.description,
      'password': instance.password,
      'taxrate': instance.taxrate,
      'acceptcheck': instance.acceptcheck,
      'visa': instance.visa,
      'mastercard': instance.mastercard,
      'amex': instance.amex,
      'discover': instance.discover,
      'active': instance.active,
      'gratuity': instance.gratuity,
      'deliverycharge': instance.deliverycharge,
      'advancenotice': instance.advancenotice,
      'printnumber': instance.printnumber,
      'drivernumber': instance.drivernumber,
      'deliverycommission': instance.deliverycommission,
      'deliveryrestaurantid': instance.deliveryrestaurantid,
      'emailserver': instance.emailserver,
      'uploadhost': instance.uploadhost,
      'firstorderdiscount': instance.firstorderdiscount,
      'cutoffhour': instance.cutoffhour,
      'country': instance.country,
      'deliverychargepercentage': instance.deliverychargepercentage,
      'deliverytippercentage': instance.deliverytippercentage,
      'numberofcompliment': instance.numberofcompliment,
      'numberofcomplaint': instance.numberofcomplaint,
      'priceend': instance.priceend,
      'pricestart': instance.pricestart,
      'level': instance.level,
      'numberofcoupons': instance.numberofcoupons,
      'partnerid': instance.partnerid,
      'm': instance.m,
      'expiration': instance.expiration,
      'mip': instance.mip,
      'twitterurl': instance.twitterurl,
      'facebookurl': instance.facebookurl,
      'neighborhood': instance.neighborhood,
      'onlinediscount': instance.onlinediscount,
      'egift': instance.egift,
      'enterpriseid': instance.enterpriseid,
      'inclusivetaxrate': instance.inclusivetaxrate,
      'wirelesswaiterhost': instance.wirelesswaiterhost,
      'ftpserver': instance.ftpserver,
      'minimumdeliverydinneramount': instance.minimumdeliverydinneramount,
      'pagename': instance.pagename,
      'pagekey': instance.pagekey,
      'ftpuser': instance.ftpuser,
      'taX3RATE': instance.taX3RATE,
      'tmip': instance.tmip,
      'ftppassword': instance.ftppassword,
      'deliverystartminutE1': instance.deliverystartminutE1,
      'deliverystartminutE2': instance.deliverystartminutE2,
      'lunchminute': instance.lunchminute,
      'lunchhour': instance.lunchhour,
      'deliveryendhouR2': instance.deliveryendhouR2,
      'deliveryendhouR1': instance.deliveryendhouR1,
      'deliverystarthouR2': instance.deliverystarthouR2,
      'deliveryendminutE1': instance.deliveryendminutE1,
      'deliveryendminutE2': instance.deliveryendminutE2,
      'deliverystarthouR1': instance.deliverystarthouR1,
      'status': instance.status,
    };
