import 'package:freezed_annotation/freezed_annotation.dart';

part 'super_restaurant_model.freezed.dart';
part 'super_restaurant_model.g.dart';

@freezed
class SuperRestaurantModel with _$SuperRestaurantModel {
  factory SuperRestaurantModel({
    int? id,
    String? restaurantname,
    String? addresslinE1,
    String? addresslinE2,
    String? crossstreet,
    String? city,
    String? state,
    String? zip,
    String? phoneareacode,
    String? phone,
    String? faxareacode,
    String? fax,
    int? minimumdeliveryamount,
    int? minimumcreditcardamount,
    int? maximumdeliverydistance,
    String? email,
    String? website,
    String? foodcategory,
    String? description,
    String? password,
    int? taxrate,
    bool? acceptcheck,
    bool? visa,
    bool? mastercard,
    bool? amex,
    bool? discover,
    bool? active,
    int? gratuity,
    int? deliverycharge,
    int? advancenotice,
    int? printnumber,
    int? drivernumber,
    int? deliverycommission,
    int? deliveryrestaurantid,
    String? emailserver,
    String? uploadhost,
    int? firstorderdiscount,
    int? cutoffhour,
    String? country,
    int? deliverychargepercentage,
    int? deliverytippercentage,
    int? numberofcompliment,
    int? numberofcomplaint,
    int? priceend,
    int? pricestart,
    int? level,
    int? numberofcoupons,
    int? partnerid,
    int? m,
    String? expiration,
    int? mip,
    String? twitterurl,
    String? facebookurl,
    String? neighborhood,
    int? onlinediscount,
    bool? egift,
    int? enterpriseid,
    int? inclusivetaxrate,
    String? wirelesswaiterhost,
    String? ftpserver,
    int? minimumdeliverydinneramount,
    String? pagename,
    String? pagekey,
    String? ftpuser,
    int? taX3RATE,
    int? tmip,
    String? ftppassword,
    int? deliverystartminutE1,
    int? deliverystartminutE2,
    int? lunchminute,
    int? lunchhour,
    int? deliveryendhouR2,
    int? deliveryendhouR1,
    int? deliverystarthouR2,
    int? deliveryendminutE1,
    int? deliveryendminutE2,
    int? deliverystarthouR1,
    int? status,
  }) = _SuperRestaurantModel;

  factory SuperRestaurantModel.fromJson(Map<String, dynamic> json) =>
      _$SuperRestaurantModelFromJson(json);
}
